export {
  VrixoClient,
  createClient,
  AuthClient,
  DatabaseClient,
  QueryBuilder,
  StorageClient,
  StorageFileApi,
  RealtimeClient,
  RealtimeChannel,
  FunctionsClient,
} from '../../../frontend/src/lib/sdk/index'

export type {
  VrixoClientOptions,
  Session,
  User,
  AuthResponse,
  AuthTokenResponse,
  AuthOAuthResponse,
  UserResponse,
  SessionResponse,
  AuthError,
  OAuthProvider,
  SignUpOptions,
  SignInWithOAuthOptions,
  ResetPasswordOptions,
  QueryOperator,
  FilterDefinition,
  OrderDirection,
  OrderDefinition,
  QueryResponse,
  PostgrestError,
  GenericResponse,
  Bucket,
  FileObject,
  FileOptions,
  SearchOptions,
  SortBy,
  DownloadOptions,
  StorageError,
  RealtimeChannel as RealtimeChannelType,
  RealtimePresence,
  RealtimePresenceState,
  RealtimeEvent,
  RealtimePostgresChangesPayload,
  FunctionDefinition,
  FunctionResponse,
  FunctionError,
  FunctionMetrics,
  AuthChangeEvent,
  AuthChangeCallback,
  Subscription,
  PostgrestFilterBuilder,
} from '../../../frontend/src/lib/sdk/types'
