apiVersion: v1
kind: Secret
metadata:
  name: vrixo-secrets
  namespace: vrixo
  labels:
    app: vrixo
type: Opaque
stringData:
  JWT_ACCESS_SECRET: ""
  JWT_REFRESH_SECRET: ""
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
  POSTGRES_USER: "vrixo"
  POSTGRES_PASSWORD: ""
  REDIS_PASSWORD: ""
  ENCRYPTION_KEY: ""
  BACKUP_ENCRYPTION_KEY: ""
  SESSION_SECRET: ""
